### ISSUE TITLE
tasks for mainnet

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1031]
- [x] beamer-bridge/product#149
- [x] beamer-bridge/beamer#1037
- [x] re-deploy frontend on hard to guess url
- [x] make new agent release
- [x] update run-you-own-agent repo
- [x] agent setup
- [x] Shutting down test mainnet agents
- [x] removing test mainnet agents from whitelist
- [x] adapt Requestmanager config (limit, fee)
- [x]  set correct url to frontend instance
- [x] https://github.com/beamer-bridge/www.beamerbridge.com/pull/12
- [x] Set minimum fee to $1 https://github.com/beamer-bridge/beamer/issues/1049

**Comment by andfletcher** [comment]
All done! :)
