### ISSUE TITLE
Making agent's claim process more robust

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1169]
The agent's claim mechanism is not designed for unreliable RPC endpoints. While we cannot account for any unreliability, we can make the process more robust.
This is currently only a collection of optimizations to make the claim process more robust. 

- [x] increase validity period in frontend
- [ ] increase min validity period in contracts
- [ ] allow MEV claiming on behalf of others
- [ ] introduce agent check that it only fills requests with X minutes validity time left 
- [ ] Allow new claims after request expiry (Used by the agent at own risk)

**Comment by fredo** [comment]
### increase validity period in frontend
Currently standard usage comes from frontend. As an easy measurement we can increase the standard validity period to 30 min. 

### increase minValidityPeriod in contracts
We can strictly forbid values lower than minValidityPeriod and need to revise the current values.

### Allow (MEV) claiming on behalf of others
Currently only who is in possession of the private key can claim for an associated address. If for whatever reason, the unit handling the private key is not able to claim then the request might expire. Similar as for challenges, it could be possible to claim on behalf of others.
In this case the game theory has to be understood and designed. The main question is, who is putting up the claim stake and takes the risk of being challenged and how or even should this entitiy be incentivized to do  so.
Additionally, an agent might want to enable or disable such a service (increasing failure risk, but getting higher rewards). The discussion seems similar to the Montiroing service in Raiden. 

Open questions:
- claim stake
- enabling/disabling
- whitelisting of specific addresses (Gelato use case)
- Incentivization schemes for external parties
- Time frames for external claiming (i.e. only if expiration date is in less than X minutes)

### Agent only fills requests with at least X minutes before expiration
The agent does not check how much time is left before a request expires. This actually means that the agent assumes that there is always enough time to fulfill a request. Due to network problems or other technical reasons, it could be the case that the agent only sees the request right before expiration. In this case, he will still try to fill and claim.
We should introduce a check that there is enough time to fill and claim a request.

Open question:
- Should this check be configurable ?

### Allow new claims after request expiry
Currently we have the following model: 
Claiming is only possible before the request expiration. After expiration it is only possible to withdraw the tokens and send them back to the user. This is a hard 0/1 requirement. 
We initially introduced this condition to enforce the agent not to fill requests after expiration. Because he wouldn't be able to claim the tokens back, it wouldn't make sense to fill it in the first place. Even if the fill was correct it would effectively be giving tokens away for free.
Thinking about this I don't see any harm to allow claims after request expiration. The effective change here would mean that a user is still able to withdraw its tokens, with the same conditions as today (there must not be any active claims), but it is also possible for an agent to claim that he filled the request. 
It still does not make sense for the agent to fill requests after expiration because the user has the option to withdraw its tokens, so most likely the agent software would not change, and the above measurements are still enhancements to the current code base.
For a rationale behaving agent it would simply be to risky filling a request which is expired or close to expiration, because he risks losing its tokens (same as in the current code base).
But if any unforeseen events happen and the agent was not able to claim a valid fill, he would still have at least the chance to rightfully claim its tokens. I don't really see a new attack vector opened to this change and don't see the point of not allowing new claims after request expiration.

**Comment by andfletcher** [comment]
Done
