### ISSUE TITLE
Be able to bridge from Arbitrum

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1271]
## Description
As a user, I want to be able to bridge USDC also to and from Arbitrum
so that assets can be sent from there or to there, and I don't need to use a different bridge or go via L1

## Acceptance Criteria
- [ ] We updated the contracts to version 1 and deployed them  and have done a successful L1 resolution test 
- [ ] Agents are able to support the Arbtirum rollup and transition from the current agent deployments to a new one
- [ ] Frontend is updated as needed and a new version is deployed
