### ISSUE TITLE
Get Faucet working on Goerli

### ISSUE THREAD

**Issue by manuelwedler** [beamer-bridge/beamer#1345]
[Faucet repo](https://github.com/beamer-bridge/faucet)

The faucet is not working since the move to Goerli.

The faucet should send test tokens to the user and a minimal amount of GoerliEth if there is enough ETH.

# Tasks
- [x] chains.json needs to be updated for the current testnet chains: Path for info: `deployments/goerli/deployment.json` , chains (base, arbitrum, optimism, Goerli).
- [x] Mint tokens to own address and send it from there to the user
- [x] Mint same amount of tokens to agent address `0xf761D67597Bcc6021BE660414a001ee88e54511a`
- [x] update server
- [x] make sure frontend's faucet button works again
