### ISSUE TITLE
Update T&S for Agents and provide them with the new version

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1355]
# Rationale
We need to update the T&S for running an agent and send it out to them.
# ToDo
- [x] Update T&S https://docs.google.com/document/d/1RnIvnipxfYZ-rXqkocjolUxOW5tXcWU-izQwNXVVfqk/edit#
- [x] Get links to add from devteam
- [x] Mail it to the agents and wait for conifmration
- [x] Provide dev team with addresses to be whitelisted
