### ISSUE TITLE
Mainnet V2 Task List

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#1626]
List for things we need to take care of before announcing. Can also link to other issues or documents: 

- [x] Deploy on Mainnet
- [x] double check configured values
- [x] Updated deployed addresses on which the relayer relies on (https://github.com/beamer-bridge/beamer/issues/1638)
- [x] run L1 resolution tests #1623 
- [x] [run agent challenge tests](https://docs.google.com/spreadsheets/d/1LDaK0vTrDzxzuo2gwM3QE0WLnbdp4dCr-7GBdg1BXpI/edit?usp=sharing)
- [x] deploy latest frontend
- [x] fund test addresses
- [x] manual testing
- [x] push deployment files to main
- [x] update contract addresses in docs
- [x] Create a Release V2.0.0
- [x] #1691
- [x] Inform agents about updates and provide any additional information they ask for. Use [this text](https://docs.google.com/document/d/13QeGXBGaoKGZXIID3gUZw9fFRlNW-JsyqGXHXRSXMXg/edit?usp=sharing)
- [x] have at least one agent ready
- [x] Replace "Live on Arbitrum" Banner on app.beamerbridge.com
- [x] Prepare Banners & assets for www.beamerbridge.com
- [x] update parameters on request managers
- [x] [double check configured parameters](https://docs.google.com/spreadsheets/d/1MK-EEpgooNCxc-cYH45Gl_zM0QluA1fjIZ_-lKoa2bg/edit?usp=sharing)
- [x] Fix remaining frontend bugs
- [x] Deploy frontend and point app.beamerbridge.com to it
- [x] Pause old Request Managers
- [ ] ...

**Comment by andfletcher** [comment]
@fredo we should use the documents we created in the past correct?

**Comment by fredo** [comment]
Yes, as I explained in dev-beamer, This is meant to be an overarching task list for additional one time tasks for this deployment.
Working of the documents we used in the past, should be one point on this list
