### ISSUE TITLE
E2E test on private optimism setup

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#165]
Currently we test L1 resolution by running it one one chain. We need to add a E2E test for the resolution mechanism on the private optimism setup.

## Tasks
- [x] Split the deployment tasks into a L1 and a L2 deployment step.
- [x] Create a way to find out about the Optimism deployment addresses and use them during deployment
  - https://github.com/ethereum-optimism/optimism/tree/develop/packages/contracts/deployments
- [x] If https://github.com/raisync-project/raisync/issues/164 has been implemented, add a script that whitelists all deployed contracts accordingly
- [x] Find out if we need to run the [message relayer](https://github.com/ethereum-optimism/optimism/tree/develop/packages/message-relayer) to forward L1/L2 messages
  - This will be necessary for mainnet, so it's probably best to create tooling for  this right away
- [x] Create a script that triggers a fill and checks for the correct effect on the source rollup
- [x] If possible, add this test to CI

## Follow-ups
- #213 
- #214
- #185
