### ISSUE TITLE
Add wrapped eth

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1685]
## Description
As a User, I want to be able to bridge wrapped eth to the beamer-connected rollups / chains so that I can use it there and don't need to use other bridges

## Todo

- [x] Support WETH in the Frontend https://github.com/beamer-bridge/beamer/pull/1980
- [x] Add WETH to contracts on all supported chains
- [x]  Make sure that contract configuration values are double checked by the teammates 
- [x] Update run-your-own-agent repo config file(s) with WETH
- [x] Inform agents about the need to provide WETH liquidity and the necessary agent config changes

## Acceptance criteria

Users are able to WETH between Beamer-connected chains, via the regular Beamer app.
