### ISSUE TITLE
Add a new command to read contract configuration

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1831]
## Reading configuration

`beamer config read --rpc-file RPC-FILE --artifact CHAIN-NAME.deployment.json CHAIN-NAME.state`

The `read` command takes an existing artifact file and a path to a (possibly non-existing)
state file. Starting from the deployment block (in case state file is not there) or from
the block specified in the state file, it then fetches all events and updates the
state. Once all contract events up to the latest block are processed, the state,
the block number and the checksum are written to the state file.

Note: updating an existing state file should be done in an atomic manner, that is,
first the command writes the new state to a temporary file and then atomically renames
the temporary file to the existing file.

If the specified state file exists, upon reading it, the command must verify the data
checksum, as described below.

### Checking consistency

Each state file has a checksum that is computed from the JSON data:

```json
{
    "block": 12345,
    "chain_id": 10,
    "checksum": "123abcf231...",
    "token_addresses": {
        "USDC": "0x1234",
        "DAI": "0x4321"
    }
    "RequestManager": {
        "min_fee_ppm": 300000,
        "lp_fee_ppm": 3000,
        "protocol_fee_ppm": 0
        "tokens": {
            "USDC": {
                "transfer_limit": 10000,
                "eth_in_token": 1800
            },
            "DAI": {
                "transfer_limit": 10000,
                "eth_in_token": 1800
            }
        },
        "whitelist": [
            "0x1",
            "0x2",
            "0x3" 
        ]
    },
    "FillManager": {
        "whitelist": [
            "0x1",
            "0x2",
            "0x3" 
        ]
    }
}
```
The checksum is computed by taking the SHA-256 of the serialized JSON content. In the above example, that would be everything without the `checksum` line.

As an illustration, given a dictionary `data` containing contract configuration as well as `block_number`,
one could use the following Python code to generate the checksum:

```python
serialized = json.dumps(data, indent=4)
serialized += '\n'
checksum = hashlib.sha256(serialized.encode('utf-8')).digest().hex()
```

Adding a newline to the end of the JSON data allows us to easily compute the checksum
without having to use a special script:
```bash
$ cat 1-ethereum.state | grep -v checksum | sha256sum
```

## Tasks

- [x] add the new `beamer config read` command
- [x] write a test for reading config from the deployment block
- [x] write a test for reading config from the block specified in the state file
- [x] write documentation

**Comment by fredo** [comment]
It's fascinating with how little code you were able to write this command ❤️
