### ISSUE TITLE
Add a new command to write contract configuration

### ISSUE THREAD

**Issue by istankovic** [beamer-bridge/beamer#1832]
## Writing configuration

`beamer config write --rpc-file RPC-FILE --artifact CHAIN-NAME.deployment.json current.state desired.state`

The `write` command takes an existing artifact file, a path to a "current" state file
and a path to the desired state file. It then issues appropriate transactions so that
the contracts' chain state reflects the desired state.

More concretely, the command does the following things, in order:

- read the current state file and note the block number, `block`
- compute the checksum and check if it matches the one written in the current state file
- if the checksums don't match, exit with an error
- read the desired state file (this one lacks both the block number and the checksum)
- get the latest block number, `latest_block`
- if `latest_block <= block`, exit with an error
- if there were any configuration changes between `block` and `latest_block`, exit with an error
- compute the set `S` of contract calls that need to be performed in order to make the desired
  state current
- for each call in `S`
  - get the current state from the RPC
  - if the desired state differs from the current state, issue a transaction to the RPC
- compute the checksum of `latest_block` and the desired state
- write the `latest_block`, checksum and the desired state to the desired state file

## Tasks

- [x] add the new `beamer config write` command
- [x] write a test for the case where no transactions need to be issued (i.e. the config on chain is already in the desired state)
- [ ] write a test that makes sure only necessary transactions are issued
- [x] write documentation

**Comment by istankovic** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Development-62442a69c5e6e60010e31cf3/issues/beamer-bridge/beamer/1832?planning-poker) with Zenhub @bilbeyt @compojoom @fredo @GabrielBuragev @manuelwedler @panpilkarz
