### ISSUE TITLE
Release new agent release that includes latest relayer fix

### ISSUE THREAD

**Issue by andfletcher** [beamer-bridge/beamer#1973]
## Description
Add PR to agent and release a new version needs to be a minor bump version
## Todo

- [x] provide information to the agents to use new artifacts 
- [x] provide information about minimum source balance 
- [x] make sure that #1959 is included
- [x] update run your own agent docs

**Comment by istankovic** [comment]
Done.
