### ISSUE TITLE
Run agent in e2e tests

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#213]
Follow-up to https://github.com/raisync-project/raisync/issues/165

In the e2e tests it would be good to also test the agent behavior.

## Tasks
- [ ] Add agent to the e2e environment
- [ ] Run the agent and issue a request
- [ ] Check that the request is filled and the agent claims it.
