### ISSUE TITLE
Live on Mainnet

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#221]
Put Boba and Metis L2 on mainnet.
Are the above both on mainnet?

Hit harder if we use Arbitrum and Optimism
Should just be an mvp on mainnet

Business
-[ ] Need to find LPs
- [ ] Discuss about rollups we support from beginning. Not having any of the leading rollups?

- [ ] Documentation on how to run an LP node
- [ ] Put Boba on mainnet
- [ ] Put Metis on mainnet

# Notes
backend:
- Remove exploitability
- Improve agent (not going down)
- Adding Arbitrum for mainnet

**Comment by czepluch** [comment]
Arbitrum and Optimism should be supported when we go live on mainnet too
