### ISSUE TITLE
Integrate zkSync

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#224]
### Rollup information

Name: 
URL:
EVM based: Yes/No
Contact: 

### Required documentation

Beamer Bridge has some requirements to integrate new rollups. It makes use of messaging layers to prove a rollup's state on L1.

#### Local testing
Please provide information on how to run a local L1/L2 deployment of the rollup.

Links to documentation:

#### Messaging
Please provide information on how to send AND retrieve arbitrary messages natively from L1 -> L2 and L2 -> L1.

Links to documentation:

#### Origin sender
Please provide information on how to prove the origin sender on the destination chain (i.e. prove the L2 origin sender on L1 for an L2 -> L1 message).

Links to documentation:

#### Source for fee calculation
Please provide information on where we can get information needed for fee calculation.

#### Contract verification
Please provide information on how to verify contracts, e.g. whether it will just work
via existing contract verification mechanisms, or if additional work is needed
(for instance, writing a new ape plugin). If additional work is needed, write relevant
issues.

### Resulting issues
Create the following issues and group them into an epic:

- [ ] Write L1 & L2 messengers
- [ ] Relayer integration
- [ ] Write an E2E test script and add id to CI workflow
- [ ] Add deployment config
- [ ] Add source for fee calculation and integrate in workflow
- [ ] Deploy on testnet
- [ ] Add rollup to testnet frontend
- [ ] Test deployment on testnet
- [ ] Deploy on mainnet
- [ ] Test deployment on mainnet
- [ ] Add rollup to frontend
