### ISSUE TITLE
Get Beamer Bridge in a demoable state

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#293]
As an end-user I want to be able to try out Beamer and make transfers by using the frontend interface so that I can provide feedback on the user experience.

## Acceptance Criteria

- [x] The frontend needs to be in a minimal functional state.
- make request
- [x] There should be at least one running agent that can fill requests.
- one running agent that is not broken in any way and which can always fill requests
- [x] The infrastructure for running an agent needs to be in place.
- [ ] ~~It should be possible to try expiring requests by requesting more than an agent can fill.~~
- [x] There should be a faucet available via the frontend where testnet tokens can be acquired.
- [x] Claiming does not need to be fully working for this demo.

**Comment by istankovic** [comment]
This is now done.
