### ISSUE TITLE
Setup faucet where testnet tokens can be acquired

### ISSUE THREAD

**Issue by taleldayekh** [beamer-bridge/beamer#313]
## Todo

- [x] Create faucet
- [x] Setup faucet infrastructure
- [x] Deploy faucet
- [x] Adapt API to feedback
- [x] Set funding amounts
