### ISSUE TITLE
Provide a way to see transfer history

### ISSUE THREAD

**Issue by czepluch** [beamer-bridge/beamer#367]
## Problem
It is not possible to get an overview of the transfers that the user had made

## Solution
Implement a view that allows the user to see a history of the transfers he's made for a given rollup. Both outgoing and incoming.

## Acceptance criteria
The user can see the successful transfers he's made and received for the network he's currently connected to. Should display:

- Amount (and what token)
- To (address and rollup)
- From (address and rollup)
- Link to relevant tx on block explorers #290 

## Todo
- [ ] Push events of filled requests to store
- [ ] Persist the store to e.g. local storage
- [ ] Visualize store data
