### ISSUE TITLE
Prepare request and fill demo

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#52]
We should prepare a small demo to showcase the working first milestone.

@taleldayekh @istankovic Feel free to add stuff here

# Tasks
- [x] Deploy contracts on a chain (optimism testnet or goerli)
- [x] Find out how to run the UI @manuelwedler 
- [x] Write some docs
