### ISSUE TITLE
Non-Fill: Trigger L1 relaying

### ISSUE THREAD

**Issue by palango** [beamer-bridge/beamer#669]
Currently the agent triggers L1 resolution only for fill proofs, but not the non-fill proof.

Depends on sending the non-fill proof in #570

## Tasks
- [ ] Decide when to trigger non-fill L1 relaying
- [ ] Add new `InitiateL1InvalidationEvent` or generalize current event
- [ ] Trigger event when non-fill proff should be relayed using L1
- [ ] Add unit tests validating the above
