### ISSUE TITLE
Fix Request Manager on Mainnet

### ISSUE THREAD

**Issue by fredo** [beamer-bridge/beamer#954]
The RequestManager is misconfigured and we need to redeploy the current Mainnet RequestManager.

### Action plan
- [x] Think again if only deploying RequestManager is fine @istankovic @fredo 
- [x] Write deployment config @fredo 
- [x] Deploy RequestManager @istankovic 
- [x] shutdown agents @istankovic 
- [x] Do two requsts on old deployment @fredo 
- [x] Withdraw one @fredo 
- [x] Deprecate RequestManager @istankovic 
- [x] Withdraw the other @fredo 
- [x] Try a new request on deprecated contract @fredo 
- [x] Update the deployment.json & affected ABI file(s) @istankovic 
- [x] Update frontend config @GabrielBuragev 
- [x] Redeploy frontend @GabrielBuragev 
- [x] Pull repo of agents @istankovic 
- [ ] Create a process of checking the values before deployment @fredo @andfletcher 
- [ ] Create a process to double/sanity check configured contracts after deployment @fredo @andfletcher

**Comment by fredo** [comment]
Also added this to this sprint @andfletcher

**Comment by fredo** [comment]
Regarding RequestManager deployment:

* Also change MAX_VALIDITY_PEROID to `30 min` (must be changed in the contract)
* Add finality period of Boba via setFinalityPeriod (288, 604800)
* change transfer limit to 50 USDC via updateTransferLimit(50000000)
* change feeData via updateFeeData 1 cent minLpFee (value = 10000)

**Comment by istankovic** [comment]
Might it make sense to move the last two items in the description into their own issue?

**Comment by fredo** [comment]
> Might it make sense to move the last two items in the description into their own issue?

I was planning the same thing, as it isn't necessarily critical for mainnet

**Comment by fredo** [comment]
created #961, will close this issue
